#!/usr/bin/env bash

title() {
    title="${USER:-$(whoami)} en ${HOSTNAME:-$(hostname)}"
}

distro() {
    . /etc/os-release
    distro="${PRETTY_NAME:-Linux}"
}

kernel() {
    read -r _ _ kernel _ < /proc/version
}

shell() {
    shell="${SHELL##*/}"
}

pkgs() {
	pkg="$(pacman -Qq | wc -l)"
}

uptime() {
    s=$(< /proc/uptime)
    s=${s/.*}

    ((d=s/60/60/24, h=s/60/60%24, m=s/60%60))

    ((d)) && uptime+="${d}d "
    ((h)) && uptime+="${h}h "
    ((m)) && uptime+="${m}m "
}

memory() {
    while IFS=: read -r a b; do
        b=${b/kB}

        case $a in
            MemTotal)((mem_used+=b,mem_total=b)) ;;
            Shmem)((mem_used+=b)) ;;
            MemFree|Buffers|Cached|SReclaimable) ((mem_used-=b)) ;;
        esac
    done </proc/meminfo

    ((mem_used/=1024,mem_total/=1024))
    memory="${mem_used}M/${mem_total}M"
}

model() {
    model="$(< /sys/devices/virtual/dmi/id/product_version) "
    model+="$(< /sys/devices/virtual/dmi/id/product_name)"
    model="${model//*O.E.M*}"
}
wm() {
  [ "$DISPLAY" ] && displayprot="x11"
  [ "$WAYLAND_DISPLAY" ] && displayprot="wayland"
  # fallback to tty if none is detected
  [ ! "$displayprot" ] && displayprot="tty"
  # get gtk theme
  while read -r line; do
    case $line in
    gtk-theme*) theme=${line##*=} ;;
    gtk-icon-theme*) icons=${line##*=} ;;
    esac
  done <"${XDG_CONFIG_HOME:-$HOME/.config}/gtk-3.0/settings.ini"
  # WMs/DEs
  # usually set by GUI display managers and DEs
  wm="$XDG_CURRENT_DESKTOP"
  [ "$wm" ] || wm="$DESKTOP_SESSION"

  # for most WMs
  [ ! "$wm" ] && [ "$DISPLAY" ] && command -v xprop >/dev/null && {
    id=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK)
    id=${id##* }
    wm=$(xprop -id "$id" -notype -len 100 -f _NET_WM_NAME 8t |
      grep '^_NET_WM_NAME' | cut -d\" -f 2)
  }

  # for non-EWMH WMs
  [ ! "$wm" ] || [ "$wm" = "LG3D" ] &&
    wm=$(
      ps -e | grep -m 1 -o \
        -e "sway" \
        -e "kiwmi" \
        -e "wayfire" \
        -e "sowm" \
        -e "catwm" \
        -e "fvwm" \
        -e "dwm" \
        -e "2bwm" \
        -e "monsterwm" \
        -e "tinywm" \
        -e "xmonad"
    )
}

{
title
distro
shell
model
uptime
memory
kernel
pkgs
wm
} 2>/dev/null

# TITULOS

#Distro="${c1} Distro"
#Shell
#Wm
#Kernel
#Memoria
#Pacman

## DEFINE COLORS

c0='[0m'
c1='[31m'; c2='[32m'
c3='[33m'; c4='[34m'
c5='[35m'; c6='[36m'
c7='[37m'; c8='[38m'
c9='^[[37m'

palette="[7m$c1 $c1 $c2 $c2 $c3 $c3 $c4 $c4 $c5 $c5 $c6 $c6 [m"

# CONEJO

ART1="${c0}   |\ |\    "
ART2="${c0}   \ \| |   "
ART3="${c0}    \ | |   "
ART4="${c0}  .--''/    "
ART5="${c0} /o     \   "
ART6="${c0} \      /   "
ART7="${c0}  {>o<}='   "

# CODIGO CONEJO
cat <<-EOF
 ${ART1}${c2}${title}${c0}     
 ${ART2}${c2}distro${c0}  ${distro}
 ${ART3}${c2}shell${c0}   ${shell}
 ${ART4}${c2}wm${c0}      ${wm}
 ${ART5}${c2}kernel${c0}  ${kernel}
 ${ART6}${c2}memoria${c0} ${memory}
 ${ART7}${c2}pacman${c0}  ${pkg}
                 $palette
EOF
